# 2.What are Tensors 什么是张量？

张量是一种特殊的数据结构，与数组和矩阵非常相似。在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。

[张量与NumPy ](https://numpy.org/)的**ndarrays**类似，不同之处在于张量可以在 GPUs 或其他硬件加速器上运行。事实上，张量和 NumPy 数组通常可以共享相同的底层内存，从而无需复制数据（请参阅[Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）。[张量还针对自动微分进行了优化（稍后我们将在Autograd](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html)部分中了解更多相关内容 ）。如果您熟悉 **ndarrays**，那么您就会熟悉 Tensor API。如果没有，那就跟随吧！

In [1]:
%matplotlib inline
import torch
import numpy as np

# Initializing a Tensor 初始化张量

张量可以通过多种方式初始化。看看下面的例子：

## Directly from data 直接来自数据

张量可以直接从数据创建。数据类型是自动推断的。

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


## From a NumPy array 自 NumPy 数组

张量可以从 NumPy 数组创建（反之亦然 - 请参阅[Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)）。由于 numpy `np_array` 和张量 `x_np` 共享相同的内存位置，因此更改其中一个的值将会更改另一个。

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Nump np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n{x_np} \n")

np.multiply(np_array, 2, out = np_array)

print(f"Nump np_array afer * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n{x_np} \n")

Nump np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 

Nump np_array afer * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



## From another tensor 从另一个张量：

新张量保留参数张量的属性（形状、数据类型），除非显式覆盖。

In [17]:
# retains the properties of x_data
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")

# overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7671, 0.1283],
        [0.3762, 0.2615]]) 



## With random or constant values 使用随机值或常数值：

`shape`是张量维度的元组。在下面的函数中，它确定输出张量的维数。

In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5888, 0.1960, 0.7622],
        [0.7147, 0.9857, 0.9080]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# Attributes of a Tensor 张量的属性

张量属性描述了它们的形状、数据类型以及存储它们的设备。

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors 张量运算

[这里](https://pytorch.org/docs/stable/torch.html)全面描述了 100 多种张量运算，包括算术、线性代数、矩阵操作（转置、索引、切片）、采样等。

这些操作中的每一个都可以在 GPU 上运行（速度通常高于 CPU）。对于样例和复习，您可以在[此处](https://pytorch.org/docs/stable/torch.html)找到全面的描述。

这些操作中的每一个都可以在 GPU 上运行（速度通常高于 CPU）。

- CPU 最多有 16 个核心。核心是进行实际计算的单元。每个核心按顺序处理任务（一次一个任务）。 
- GPU 有 1000 个核心。 GPU 核心以并行处理方式处理计算。任务在不同的核心之间划分和处理。这就是大多数情况下 GPU 比 CPU 更快的原因。 GPU 在处理大数据时比处理小数据时表现更好。 GPU 通常用于图形或神经网络的高强度计算（我们稍后将在神经网络单元中了解更多信息）。 
- PyTorch 可以使用 Nvidia CUDA 库来利用其 GPU 卡。

默认情况下，张量是在 CPU 上创建的。我们需要使用 `.to`方法显式地将张量移动到 GPU（在检查 GPU 可用性之后）。请记住，跨设备复制大张量在时间和内存方面可能会很昂贵！ory!

In [18]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

尝试列表中的一些操作。如果您熟悉 NumPy API，您会发现 Tensor API 使用起来非常简单。

## Standard numpy-like indexing and slicing 标准的类似 numpy 的索引和切片：

In [8]:
tensor = torch.ones(4, 4)
print(f"Ones Tensor:\n {tensor} \n") 
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(f"Ones Tensor:\n {tensor} \n") 

Ones Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
Ones Tensor:
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



## Joining tensors 连接张量

**连接张量**您可以使用它[`torch.cat`](https://pytorch.org/docs/stable/generated/torch.cat.html) 来沿**给定维度**连接一系列张量。[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)是一个相关的张量连接选项，它沿着新维度连接一系列张量。

In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.]], device='cuda:0')


## Arithmetic operations 算术运算

In [10]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Single-element tensors 单元素张量

**单元素张量**如果您有一个单元素张量，例如通过将张量的所有值聚合为一个值，您可以使用以下方法将其转换为 Python 数值`item()`：

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


## In-place operations 就地运算

 **就地运算** 将结果存储到操作数中的操作称为就地运算。它们由`_`后缀表示。例如：`x.copy_(y)`、`x.t_()`、 将会改变`x`。

In [12]:
print(f"{tensor} \n")
tensor.add_(5)
print(f"{tensor} \n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



### Note 笔记


就地操作可以节省一些内存，但在计算导数时可能会出现问题，因为历史记录会立即丢失。因此，不鼓励使用它们。

# Bridge with NumPy 与 NumPy 的桥梁

CPU 和 NumPy 数组上的张量可以共享其底层内存位置，改变其中一个就会改变另一个。

## Tensor to NumPy array 张量到 NumPy 数组

In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


张量的变化反映在 NumPy 数组中。

In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor NumPy 数组到张量

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


NumPy 数组中的变化反映在张量中。

In [16]:
np.add(n, 1, out = n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# 知识检查

张量是类似于数组和矩阵的专用数据结构。

# References 参考资料

使用 PyTorch 进行机器学习的简介 - Training | Microsoft Learn

[使用 PyTorch 进行机器学习的简介 - Training | Microsoft Learn](https://learn.microsoft.com/zh-cn/training/modules/intro-machine-learning-pytorch/)

# Github

storm-ice/PyTorch_Fundamentals

[storm-ice/PyTorch_Fundamentals](https://github.com/storm-ice/PyTorch_Fundamentals/tree/main)h)